### ISSUE TITLE
Question about Z-scores

### ISSUE THREAD

**Issue by michael-mazzucco** [RWParsons/circacompare#6]
Hello circacompare team, I have a small issue I am hoping you might be able to help with. Apologies for the long reprex but I can't seem to run my dataset after Z scoring and was hoping for tips. The basic premise is that I want to look at genes between stiff and not_stiff RA patients over a couple of day period. One concern I had was patient level interference so I wanted to test if the Z scores would yield cleaner but the below shows my issue. Also when I run more columns I get the error: 

Error in stats::nls(formula = form_group, data = x, start = start_list_grouped(g1 = g1_model$model,  : 
  step factor 6.10352e-05 reduced below 'minFactor' of 0.0001

Which doesn't seem to prevent the function from working but nonetheless confusing. Any direction is appreciated, thank you!

``` r
# Reprex for Git

# Set the wd
setwd("~/Dropbox/Mazzucco - Circadian RA Project/master_manuscript/Figure5_circacompare")

# Load in the libraries
suppressPackageStartupMessages({
  library(tidyverse)
  library(circacompare)
  library(progress)
  library(reprex)
})
# Load in the lcpm Z-scored
zscores_by_patient <- read.delim("input_tables/zscores_per_patient_matrix_lcpm_06062023.tsv") %>%
  column_to_rownames(var = "ID")

# Load in lcpm for amplitude
load(file = "R_objects/lcpm_ucsc_05162023.RData") 

# Metadata
meta <- read_csv("input_tables/meta_cbc.csv")
#> Rows: 92 Columns: 18
#> ── Column specification ────────────────────────────────────────────────────────
#> Delimiter: ","
#> chr  (6): FASTQ_ID, Title, Patient, stiffness, Sample, Event_Name
#> dbl (12): time, time_of_collection, replicate, cortisol, WBC, ESR, CRP, neut...
#> 
#> ℹ Use `spec()` to retrieve the full column specification for this data.
#> ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
meta_circa <- meta[,c(1,5,7)]

# Set up inputs
lcpm <- t(as.data.frame(lcpm))
to_bind_lcpm <- rownames_to_column(as.data.frame(lcpm), "FASTQ_ID")
circa_input_lcpm <- left_join(meta_circa, to_bind_lcpm, by = "FASTQ_ID")

zscores_by_patient <- t(as.data.frame(zscores_by_patient))
to_bind_z <- rownames_to_column(as.data.frame(zscores_by_patient), "FASTQ_ID")
circa_input_z <- left_join(meta_circa, to_bind_z, by = "FASTQ_ID")

# Subset to run
circa_test_lcpm <- circa_input_lcpm[,1:10]

circa_test_z <- circa_input_z[,1:10]

# Write the function
run_circacompare <- function(circa_input, col_time, col_group, start_col) {
  # Initialize the output data frame
  out_df <- NULL
  
  # Create a progress bar
  pb <- progress_bar$new(total = ncol(circa_input) - start_col + 1)
  
  # Loop over the columns of circa_input starting from start_col to the last column
  for (num in start_col:ncol(circa_input)) {
    # Run circacompare on the current column
    out_table <- try(circacompare(x = circa_input, col_time = col_time, col_group = col_group,
                                  col_outcome = colnames(circa_input)[num], alpha_threshold = 0.9999), silent = TRUE)
    
    # Check if circacompare was successful
    if (!inherits(out_table, "try-error")) {
      # Convert the summary to a data frame and rename the second column
      output_df2 <- data.frame(out_table$summary)
      colnames(output_df2)[2] <- colnames(circa_input)[num]
      
      # If out_df is NULL (i.e., this is the first iteration), set it to output_df2
      # Otherwise, bind the second column of output_df2 to out_df
      if (is.null(out_df)) {
        out_df <- output_df2
      } else {
        out_df <- cbind(out_df, output_df2[,2, drop = FALSE])
      }
    }
    
    # Update the progress bar
    pb$tick()
  }
  
  # Convert the 'parameter' column to row names, transpose the data frame, and remove the second row
  out_df <- column_to_rownames(out_df, var = 'parameter')
  t_out <- t(out_df)
  t_out <- t_out[-2,]
  
  # Return the final data frame
  return(t_out)
}

# Run the function
test_lcpm <- run_circacompare(circa_test_lcpm, 'time_of_collection', 'stiffness', 4)

test_z <- run_circacompare(circa_test_z, 'time_of_collection', 'stiffness', 4)
#> Failed to convergenot_stiff model prior to timeout. 
#> You may try to increase the allowed attempts before timeout by increasing the value of the 'timeout_n' argument or setting a new seed before this function.
#> If you have repeated difficulties, please contact me (via github) or Oliver Rawashdeh (contact details in manuscript).
#> Error in names(x) <- value: 'names' attribute [2] must be the same length as the vector [0]

# Look at circa for one each
circacompare(x = circa_test_lcpm, col_time = "time_of_collection", 
            col_group = "stiffness", col_outcome = "A1BG", alpha_threshold = 0.9999)
#> $plot
```

![](https://i.imgur.com/gZo7EWD.png)

    #> 
    #> $summary
    #>                                          parameter         value
    #> 1  Presence of rhythmicity (p-value) for not_stiff  2.810219e-01
    #> 2      Presence of rhythmicity (p-value) for stiff  3.508367e-01
    #> 3                         not_stiff mesor estimate  3.340200e+00
    #> 4                             stiff mesor estimate  3.812759e+00
    #> 5                        Mesor difference estimate  4.725590e-01
    #> 6                     P-value for mesor difference  3.669353e-09
    #> 7                     not_stiff amplitude estimate  8.053901e-02
    #> 8                         stiff amplitude estimate  6.440263e-02
    #> 9                    Amplitude difference estimate -1.613638e-02
    #> 10                P-value for amplitude difference  8.732029e-01
    #> 11                       not_stiff peak time hours  6.629319e+00
    #> 12                           stiff peak time hours  8.054797e+00
    #> 13                       Phase difference estimate  1.425478e+00
    #> 14                 P-value for difference in phase  7.951175e-01
    #> 15                          Shared period estimate  2.400000e+01
    #> 
    #> $fit
    #> Nonlinear regression model
    #>   model: measure ~ (k + k1 * x_group) + ((alpha + alpha1 * x_group)) *     cos((1/period) * time_r - ((phi + phi1 * x_group)))
    #>    data: x
    #>        k       k1    alpha   alpha1      phi     phi1 
    #>  3.34020  0.47256  0.08054 -0.01614  1.73555  0.37319 
    #>  residual sum-of-squares: 10.15
    #> 
    #> Number of iterations to convergence: 8 
    #> Achieved convergence tolerance: 2.853e-07

    circacompare(x = circa_test_z, col_time = "time_of_collection", 
                 col_group = "stiffness", col_outcome = "A1BG", alpha_threshold = 0.9999)
    #> Failed to convergenot_stiff model prior to timeout. 
    #> You may try to increase the allowed attempts before timeout by increasing the value of the 'timeout_n' argument or setting a new seed before this function.
    #> If you have repeated difficulties, please contact me (via github) or Oliver Rawashdeh (contact details in manuscript).

<sup>Created on 2023-06-20 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by RWParsons** [comment]
Hi Michael,

I can't run any of your code without the data to test anything myself but it doesn't appear that you're doing anything drastically wrong from my POV.

As for the first warning, circacompare works by attempting to fit the model over and over until it achieves convergence and the estimated parameters are in sensible ranges (i.e. the amplitude is positive and the phase shift between groups is less than half the period in either direction). This warning (and failure to converge) will have occurred during one of these earlier model fitting attempts. I have chosen to allow these to be shown to the user because they can be informative to the user at times. For example, if the model is over parameterised, the user should be able to see these warnings, google them, and find out that it may be associated with an overparameterised model.

For the second failure with `col_outcome = "A1BG"`, this happened because it failed to get a model to converge with sensible parameter estimates in the first `n_timeout` attempts (the default is 10000). To be honest, if all your data are as noisy and small as in the graphic, then the model may just be close to being over parameterised. You can try to fit it still while increasing `timeout_n = 50000 ` or so and see if it eventually works. Or, since (afaik) you're normalising data within patients (and, therefore, indirectly normalising amplitude within groups), you are probably more interested in identifying phase shifts rather than differences in amplitude(?) If this is the case, then you can choose to force both groups to have the same amplitude and avoid having to estimate that extra parameter. There are examples of how to adjust the parameterisation of the model in the vignette here <https://cran.r-project.org/web/packages/circacompare/vignettes/circacompare-vignette.html>. Please let me know if this helps and whether you're happy for me to close this issue.

Cheers,
Rex

**Comment by michael-mazzucco** [comment]
Hi Rex, 

Thank you for the speedy reply! I went through your comment and attached link this all makes sense to me. Feel free to close the issue, hopefully this can help others who have the same questions I did. Much appreciated, love the package!

**Comment by RWParsons** [comment]
Happy to help - thanks, Michael!
